spring:
  application:
    name: api
  profiles:
    active: local
  jpa:
    open-in-view: true
server:
  port: 8880
  servlet:
    context-path: /api

management:
   endpoints:
    web:
      exposure:
        include: "health"