#    assigned	                a user is assigned to the pull request
#    unassigned       	        a user is unassigned from the pull request
#    labeled	                a label is applied to the pull request
#    unlabeled        	        a label is removed from the pull request
#    opened	                    pull request is created
#    edited	                    title, body, or the base branch of the PR is modified
#    closed	                    pull request is closed (as opposed to merged)
#    reopened	                closed pull request is reopened
#    synchronize	            commit(s) pushed to the pull request
#    ready_for_review	        pull request is taken out from draft mode
#    locked	pull                request is locked
#    unlocked	                pull request is unlocked
#    review_requested	        request a user for review
#    review_request_removed	    remove request from user for review

name: Master pull request opened
run-name: ${{ github.actor }} is mergin branch to main

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    branches:
      - main
jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./api/gradlew build