###____________________________ SECTORS
GET localhost:8880/api/sectors

###____________________________ SECTORS
DELETE localhost:8880/api/sectors/1


###____________________________ USERS
GET localhost:8880/api/users?sortBy=id&pageNumber=0&pageSize=2

###

POST localhost:8880/api/users
Content-Type: application/json

{"name":"tete5","sectorNames":["child 2"],"agreeToTerms":true}

###
PUT localhost:8880/api/users/3
Content-Type: application/json

{"name":"AB5","sectorNames":["child 2"],"agreeToTerms":true}

###

POST localhost:8880/api/users
Content-Type: application/json

{
  "name":"tetqe25",
  "sectorIds":[15, 70],
  "agreeToTerms":true
}